### ISSUE TITLE
Integration with Evil

### ISSUE THREAD

**Issue by z0rch** [syohex/emacs-anzu#39]
With [Evil](http://www.emacswiki.org/emacs/Evil) installed:

* Press `/` to start incremental search.
* Type "text" -> anzu will show `(1/5)` in mode line
* Hit `Enter` to start searching, use `n` and `N` to navigate.

After you hit `Enter`, anzu information disappears from the mode line. This is fine, because selection also disappears. But when you press `n` or `N`, selection reappears for a couple of seconds, and cursor moves to the next/previous match.

I expect anzu information also to appear for a couple of seconds after I press `n` or `N`.

Currently, anzu information does not appear after hitting `n` or `N`.

---------------------------------------------

Maybe I am missing something obvious here?

I can see that `vim-anzu` provides the following mappings

```
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
```

Is there a similar configuration to remap evil's `n` and `N`?

**Comment by syohex** [comment]
I'm not evil user and I don't understand evil well.
I'll check anzu with evil.

**Comment by syohex** [comment]
It is difficult to use current anzu with evil.

I implement `evil-anzu` as prototype.
Code is [here](https://gist.github.com/syohex/bc8fa1a73c5140f10e89)

Here is screencast of `evil-anzu`.

![evil-anzu](https://cloud.githubusercontent.com/assets/554281/5676318/53836272-9817-11e4-88a8-f0c13ca3e467.gif)

I need to study more about evil.

**Comment by z0rch** [comment]
@syohex, I've tried your prototype, it works quite nice! :+1: 

Are you considering to create a separate github repo for `evil-anzu`? It would be nice to have a centralized place for feature suggestions, bug fixes, etc.

Ideally I'd love to install it with package manager, to receive future updates, if any :smile: 

---------------

I have one UX suggestion (this is something I would rather report in its own repo). 
Check out the following use case:

1. Hit `/` and type some text -> number of matches is visible (OK)
![image](https://cloud.githubusercontent.com/assets/1177900/5683601/80652ca0-9829-11e4-832b-380229c3c498.png)
2. Hit `Enter` -> cursor moved to the first match, number of matches is not visible (OK)
![image](https://cloud.githubusercontent.com/assets/1177900/5683649/e1f87b2a-9829-11e4-9c4c-e607cd9c3f76.png)
3. Hit `n` -> cursor moved to the next match, number of matches is visible (OK)
![image](https://cloud.githubusercontent.com/assets/1177900/5683616/91372dee-9829-11e4-8118-91ab6ce703c3.png)
4. Wait a couple of seconds, all matches stop being highlighted, but anzu still displays the number of matches (**NOT OK**)
![image](https://cloud.githubusercontent.com/assets/1177900/5683620/97aa5fe8-9829-11e4-8fad-f3c3ca12c43a.png)

I expect this counter to disappear as soon as highlighting drops.

**Comment by syohex** [comment]
> Are you considering to create a separate github repo for evil-anzu?

Yes.

Thanks for information. I'll try to fix them.

**Comment by z0rch** [comment]
I'm closing this issue since it has been fixed in [emacs-evil-anzu](https://github.com/syohex/emacs-evil-anzu) repository.

Thanks again, @syohex!
