### ISSUE TITLE
Add spaces around expression in mode-line

### ISSUE THREAD

**Issue by fniessen** [syohex/emacs-anzu#55]
Would you accept adding one space before and one space after the expressions such as "(%d/%d)"?
Or add an option?  

That'd allow us not to redefine several functions if we want such a display.

Thanks!

**Comment by syohex** [comment]
You can write custom mode-line update function like following code.
If `anzu-mode-line-update-function` is non-nil and set function, `anzu.el` uses it for updating mode line.


```
(defun my/anzu-update-func (here total)
  (when anzu--state
    (let ((status (cl-case anzu--state
                    (search (format "( %d / %d )" here total))
                    (replace-query (format "(%d Replaces)" total))
                    (replace (format "( %d / %d )" here total)))))
      (propertize status 'face 'anzu-mode-line))))
(setq anzu-mode-line-update-function #'my/anzu-update-func)
```

**Comment by fniessen** [comment]
I'm wondering how it'd be written to handle the "1000+" limit for example.

But I'm not using it right now, so I can safely close this. Thanks a lot!

**Comment by syohex** [comment]
> I'm wondering how it'd be written to handle the "1000+" limit for example.

@fniessen Please see `anzu--update-mode-line-default` function. You can check it
by value of `anzu--overflow-p`.

```lisp
(defun anzu--update-mode-line-default (here total)
  (when anzu--state
    (let ((status (cl-case anzu--state
                    (search (format "(%s/%d%s)"
                                    (anzu--format-here-position here total)
                                    total (if anzu--overflow-p "+" "")))
                    (replace-query (format "(%d replace)" total))
                    (replace (format "(%d/%d)" here total)))))
      (propertize status 'face 'anzu-mode-line))))
```
