### ISSUE TITLE
[Feature Request] replace globally in current things

### ISSUE THREAD

**Issue by zw963** [syohex/emacs-anzu#56]
e.g.

```ruby
def as_indexed_json(options = {})
    _attributes = attributes.as_json
    _attributes["status"] ||= 0  <== cursor is here
    _attributes.as_json(:except => "additional_fields")
end
```

run (anzu-replace-at-cursor-thing), it just replace last _attributes,
replace worked like this, but, I thought if I definition myself thing,
I hope can replace 3 occur _attributes in current method.

Thanks.

**Comment by syohex** [comment]
Sorry too late reply.

![orig](https://cloud.githubusercontent.com/assets/554281/8647629/9d96d358-2994-11e5-82b9-ac9782eb4a33.gif)

If cursor is there, `anzu-replace-at-cursor-thing` replaces nothing and say `No symbol at cursor!!`.
You can replace 3 `_attributes` by moving cursor to each `_attributes` position.

![orig](https://cloud.githubusercontent.com/assets/554281/8647610/737ce472-2994-11e5-9091-49e69319efc3.gif)

**Comment by zw963** [comment]
Thank very much.

I create myself `def` things like following, but it seem like not work correctly.
(only change the last _attributes)

```ruby
            (defun beginning-def (&optional arg)
              (interactive)
              (enh-ruby-beginning-of-defun arg))
            (defun end-def (&optional arg)
              (interactive)
              (enh-ruby-end-of-defun arg))
            (defun forward-def (&optional arg)
              (interactive)
              (enh-ruby-forward-sexp arg))
            (setq anzu-replace-at-cursor-thing 'def)
```

I remove all this, use default `defun`, it worked!
