### ISSUE TITLE
Priority of `anzu-match-{1,2,3}` faces

### ISSUE THREAD

**Issue by d125q** [syohex/emacs-anzu#68]
Should the `anzu-match-{1,2,3}` faces be put with a higher priority?  Either they are overriden by `isearch`, or I do not know where they're supposed to appear.

**Comment by syohex** [comment]
No it should not. They are only for replace commands, not search commands.

**Comment by d125q** [comment]
Thanks.  Can you please give me an example where these faces are supposed to be used?  I've never seen them despite using `anzu-query-replace`.

**Comment by syohex** [comment]
You can use them at `anzu-query-replace-regexp`. Gif animation is here.

![anzu](https://cloud.githubusercontent.com/assets/554281/12842841/afe5f876-cc38-11e5-9c6f-7b7fb6cd7522.gif)
