### ISSUE TITLE
replace isearch-query-replace-regexp to anzu search.

### ISSUE THREAD

**Issue by zw963** [syohex/emacs-anzu#71]
I often use replace like following:

### step one:
Search something with C-s

### step two:
If found, invoke `isearch-query-replace-regexp` with a shortcut,
it can use isearch result as search, and ask the replace strings.

Thanks.

**Comment by syohex** [comment]
Thanks suggestion.
I have implemented these commands at #72. Please check latest version.

Sample configuration is here.
```lisp
(define-key isearch-mode-map (kbd "M-%") #'anzu-isearch-query-replace)
(define-key isearch-mode-map (kbd "C-M-%") #'anzu-isearch-query-replace-regexp)
```

**Comment by zw963** [comment]
It worked, Thanks.

though, i need bindkey within isearch hook, make it run once when `Ctrl+S`.

```cl
(add-hook 'isearch-mode-hook
          '(lambda ()
             (define-key isearch-mode-map [(meta \5)] 'anzu-isearch-query-replace-regexp)
))
```

**Comment by zw963** [comment]
directly bind like example is not worked.

**Comment by syohex** [comment]
> directly bind like example is not worked for me, emacs 24.3

Thanks for information. I'll check and update document if necessary.

**Comment by syohex** [comment]
> directly bind like example is not worked for me, emacs 24.3

It is work on my environment, hmm.

**Comment by zw963** [comment]
Sorry,  I test with emacs -Q, example work fine for me.

I test my own dotfiles, find some hook restore to default keybinding ...

After fix this,  it worked now ...

Thanks.

**Comment by zw963** [comment]
One more question please ... 

Following expression is equivalent ? thanks.

```cl
(define-key isearch-mode-map (kbd "M-%") #'anzu-isearch-query-replace)
```
```cl
(define-key isearch-mode-map (kbd "M-%") 'anzu-isearch-query-replace)
```

**Comment by syohex** [comment]
They are equivalent except that Emacs warns `#'`ed function if it is not defined at byte-compile time.
