### ISSUE TITLE
Case-Sensitive Replace

### ISSUE THREAD

**Issue by goldsborough** [syohex/emacs-anzu#74]
I'm having problems trying to do case-*sensitive* Regex-Replacing with Anzu. I've enabled `anzu-query-replace-regexp` in my `.emacs` like so:

```elisp
(global-set-key (kbd "C-r") 'anzu-query-replace-regexp)
```

Now the problem is that the replacement function seems to be case-*insensitive*, which really sucks and also makes no sense because it's regular expressions. I've tried toggling `case-fold-search` and also tried this snippet:

```elisp
(global-set-key (kbd "C-r")
                 (lambda ()
                  (interactive)
                   (let ((case-fold-search nil))
                     (call-interactively 'anzu-query-replace-regexp))))
```

But neither seem to make the replacement-search case-*sensitive*. Any suggestions?

**Comment by syohex** [comment]
Thanks for reporting issue. I didn't consider users's `case-fold-search`. I've fixed it at #75. Please check latest version.
