### ISSUE TITLE
anzu-query-replace-regexp dies if `^` is input as pattern on a region

### ISSUE THREAD

**Issue by knu** [syohex/emacs-anzu#79]
Steps to reproduce:

1. Activate a region (`C-SPC`) and select at least two lines (`C-n C-n`)
2. Invoke `M-x` `anzu-query-replace-regexp`
3. Hit `^`

And you'll see a Lisp error: `Invalid search bound (wrong side of point)`

A backtrace shows it is raised in `re-search-forward` called by `anzu--count-and-highlight-matched`.

**Comment by syohex** [comment]
I think this issue is fixed by #80. Please check latest version.

**Comment by knu** [comment]
Thanks!  Just confirmed the latest snapshot has fixed the problem.
