### ISSUE TITLE
Nice to have: different face for failure

### ISSUE THREAD

**Issue by fniessen** [syohex/emacs-anzu#83]
Hello. Super tool I already use for years now... Don't understand this isn't basic into Emacs yet, but that's another story.

Now, my wish would be to have a different face when there is no match. For example, we could then have the indicator in the modeline:

- with a green background when there are matches,
- with a red background as soon as we search for a pattern that's not present in the buffer.

That'd visually help to focus on the searches.

Thanks for considering it!

UPDATE -- In fact, the more general approch would consist in having 3 faces: one when there "0 out of 0 matches" (= nothing found, or nothing specified yet), another when there are "xx out of yy matches" (where xx < yy = many possible matches) and finally one when there are "xx out of yy matches" (where xx = yy, that is only one match available).

**Comment by syohex** [comment]
How about #86 ?

**Comment by fniessen** [comment]
I think that adding another face, anzu-mode-line-one-match, would be wonderful. That could prove as being of a great help when quickly typing. Great feedback.

However, this is already a very nice add-on, and I thank you for that. Closing the issue.

**Comment by syohex** [comment]
I think it is enough to add only `anzu-mode-line-no-match`.

**Comment by fniessen** [comment]
Your call. I respect it.

Thanks for the update, anyway!
