### ISSUE TITLE
feature request: Anzu in iedit

### ISSUE THREAD

**Issue by mookid** [syohex/emacs-anzu#87]
[iedit](https://github.com/victorhge/iedit) provide some functionalities that overlap isearch; from iedit mode, you can navigate from one match to the previous/next one.

The current implementation provides a count for the number of matches, but no information about the current match. It would be nice to be able to get `anzu` working in `iedit mode` too.

**Comment by syohex** [comment]
I think it is enough to provide current features. I don't want to make complex anymore. I think it is better to create new package like `anzu-iedit` or adding new features to `iedit` rather than adding new features to `anzu` itself.
