### ISSUE TITLE
The display in modeline is not accurate now

### ISSUE THREAD

**Issue by basheewang** [syohex/emacs-anzu#94]
I am using latest master source compiled emacs. Recently I found the Anzu doesn't work as before.
The total matched number are correct, but the current number isn't correct and bigger than the total number.

For example, I will emacs -Q to start, then M-x package-list-packages, then isearch "tree", there are 11 matches, use C-s to navigate, there will be **1/11**, **2/11**, then **4/11**, no **3/11**.

My emacs version:
GNU Emacs 27.0.50 (build 15, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2018-10-09

**Comment by petercheng00** [comment]
I have been seeing the same incorrect behavior on version
"GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2018-06-15"

**Comment by shwaka** [comment]
The following code (in `init.el`) fixes the issue, at least for me.
```elisp
(defun override:anzu--where-is-here (positions here)
  (let ((index (seq-position positions here
                             (lambda (pos h)
                               (let ((start (car pos))
                                     (end (cdr pos)))
                                 (and (>= h start) (<= h end)))))))
    (if index (1+ index) 0)))
(advice-add 'anzu--where-is-here :override 'override:anzu--where-is-here)
```

Note that the issue is caused by a bug of `cl-loop` ([#33890 - 27.0.50; Incorrect behaviour of cl-loop macro - GNU bug report logs](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33890)).
The above code has the same effect as the original `anzu--where-is-here` in emacs 26,
but it does not use `cl-loop`.

**Comment by syohex** [comment]
@basheewang , @petercheng00  sorry very belated reply. Could you try to latest version ?

@shwaka thanks for information :bowing_man:

**Comment by petercheng00** [comment]
Latest version works, thanks @shwaka and @syohex!
